language: python
sudo: enabled
dist: trusty
group: edge

# whitelist master/development branch only		
branches:		
  only:		
    - master
    - development

before_install:
  - sudo apt-get update

install: ./.travis_ci/prepare.sh

script: ./run_tests.sh

after_success: /bin/bash upload_image.sh

after_failure: /bin/bash upload_image.sh