doc:
  property:
  - password: ''
  - groups: ''
  - g8client: ''
  - email: ''
  - provider: ''
  - uservdc: 'List of vdc users that cann access the machine'
links:
  consume:
  - argname: g8client
    auto: true
    max: 100
    min: 0
    role: g8client
    argname: 'g8client'
  - argname: uservdc
    auto: false
    max: 100
    min: 0
    role: uservdc
recurring: []
