doc:
  property:
  - g8client: ''
  - devicename: ''
  - type: ''
  - maxIOPS: ''
  - description: ''
  - size: disk size in GB
  - ssdSize: ''
  - location: ''

links:
  consume:
  - argname: g8client
    auto: true
    min: 1
    max: 100
    role: g8client

recurring: []
